---
- hosts: dev_webservers
  remote_user: ubuntu
  become: true
  vars_files:
    - group_vars/VAULT
    - group_vars/webservers.yml
    - host_vars/labs.neoformit.com.yml
  roles:
    - role: geerlingguy.docker
      tags: init
    # - role: geerlingguy.postgresql
    #   become: true
    - galaxy_labs_engine
